**1. Import numpy as np and see the version (Score 1)**

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


**2. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5**


In [ ]:
arr = np.arange(1,11)
print(arr)
arr.reshape(2,5)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**3. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.**

In [ ]:
arr_1 = np.arange(1,21)
print(arr_1)
print(arr_1[5:16])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15 16]


**4. How to compute the mean, median, standard deviation of a numpy array?Use the array you created above**

In [ ]:
print("Mean:",np.mean(arr_1))
print("Median:",np.median(arr_1))
print("Standard Deviation:",np.std(arr_1))


Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


**Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting.**

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([1, 2, 3, 4])
result = a - b
print(result)

[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]
